# Generated by scripts/update.sh from Valve's client manifest. Do not edit.
{
  channel = "publicbeta";
  version = "1789086785";
  baseUrl = "https://client-update.fastly.steamstatic.com";
  components = {
    tenfoot_images_all = {
      file = "tenfoot_images_all.zip.86419c7a56c12dd107b5e0d46f50c8a9b121f3cc";
      sha256 = "990676bc29d01736477c6b571b5048258a6156284ef242503112fc68567cbf01";
    };
    steamui_websrc_all = {
      file = "steamui_websrc_all.zip.d3c6e25ffad894fe4d75c28dd8331d6bbc0e5ec6";
      sha256 = "5318336d655cd08a3830d72a5a67fc44cb2df6314fce0dfba7477e072cb18ea6";
    };
    resources_misc_all = {
      file = "resources_misc_all.zip.99ed79ed868d732d8e9e9a45444b8f003191e3dd";
      sha256 = "187e562403c7544af7162e08baf7677d030ad6f60947c2cdc7dcbcbf0a7a7fe6";
    };
    resources_hidpi_all = {
      file = "resources_hidpi_all.zip.a110d78e994c028dc1c412951e87a0c4e9c819f7";
      sha256 = "5bdb97ec734f035c1d06a59b62980028b1b05b920c544ae3673b1a515d3d507e";
    };
    resources_all = {
      file = "resources_all.zip.213fe769fd8484a0d149453c5655e70c1d13b086";
      sha256 = "769840cdb2b22ad9798a1a3950de2fe82b8b5d3d37389dcc9b1393f77480d67b";
    };
    strings_en_all = {
      file = "strings_en_all.zip.e716a67d7fa91ba70490a6417e25d45c5435e393";
      sha256 = "0c56193fac4fa518eaaac0dc66ecd21a3cee510ece85594b6c308f8d31ee98a3";
    };
    strings_all = {
      file = "strings_all.zip.ad0779a3a2612ae06fe66604b121245d3905fd12";
      sha256 = "5a5370f3b16675cc39d928d8557ff42f4f6caa427ea4d6bc7f98ee31d8ef9513";
    };
    public_all = {
      file = "public_all.zip.ef52370f4e237d06ef1a4641e253043a40ebb507";
      sha256 = "70442e3715002aef646bcfcd6c27ccfb2ef76fae8690efd15157c118e3666614";
    };
    bins_hardware_all = {
      file = "bins_hardware_all.zip.ff20d8eee360c5ab7bf18b8ee6829d907f20794d";
      sha256 = "db5cb312aeb0f0ec67bf050664e8702511d6092cd2caca4861b406d481bfbc70";
    };
    steamui_websrc_sounds_all = {
      file = "steamui_websrc_sounds_all.zip.74727ca40ef88c5012bb631488fd285418dce825";
      sha256 = "c823bd39d234e7d9a5fdb5ec6605eae3f175e52bb847725e8826ff526a61641c";
    };
    steamui_websrc_movies_all = {
      file = "steamui_websrc_movies_all.zip.40e78cdda48e9a8a74baf614e0cdc7a6b96d26d1";
      sha256 = "885a32533327f0fd5ea98e6c6f13552e965cab4852dad7ce9ccf3d929d726b5b";
    };
    webkit_linuxarm64_linuxarm64 = {
      file = "webkit_linuxarm64_linuxarm64.zip.c1d5fa58a564375f71b34bccaa51c19be1143137";
      sha256 = "b8687e0f20668d24055d8f2e9f6c4fbcbe84fbb99a7bc9de4595530be7029990";
    };
    sdl3_linuxarm64_linuxarm64 = {
      file = "sdl3_linuxarm64_linuxarm64.zip.70606d2fc08abc9fbfad9abc219baa0df3c83844";
      sha256 = "8f5af5323c76c002f7ad77fc0b734df8019629cad25afb70a5dcc4a39ec42302";
    };
    codecs_linuxarm64_linuxarm64 = {
      file = "codecs_linuxarm64_linuxarm64.zip.b27e1d78cec034a8c73b0ff1bc6acbe3b8586344";
      sha256 = "8e77a5e4605d7c7b576ce64abf39cfd342aea8d6783e17f2fb91e1c8f4357a0f";
    };
    bins_linuxarm64_linuxarm64 = {
      file = "bins_linuxarm64_linuxarm64.zip.9c3936cfc37f53036e1a91fc6ae2b298d99350eb";
      sha256 = "04bd7d34bed4f492fe0e8ed77d489d3cf7ae49247372c46ea09e20bb087ded10";
    };
    bins_sdk_linuxarm64_linuxarm64 = {
      file = "bins_sdk_linuxarm64_linuxarm64.zip.76420cc04891e2528f33340ab667a308c3b0d8b3";
      sha256 = "3beee9b0919759967553a39880bbc637557eeee2b5e041395aab6e8fca0d0ddf";
    };
    resource_linuxarm64_linuxarm64 = {
      file = "resource_linuxarm64_linuxarm64.zip.6e5691ac5a1a55a554250468a98c3f8e454fea4a";
      sha256 = "f78280db38d95a74096a00f7d2bc3061286db135e9e61bbf963eb65de39d66fc";
    };
  };
}
