# Generated by scripts/update.sh from FEX's rootfs index. Do not edit.
{
  url = "https://rootfs.fex-emu.gg/Fedora_44/2026-08-11/Fedora_44.ero";
  hash = "sha256-2yUDxP8kouDTmrFp0FoTqRICsm0uhzI0AMxRtGpuHFg=";
}
