# Generated by scripts/update.sh from Valve's runtime index. Do not edit.
{
  snapshot = "3c.0.20260729.253765";
  baseUrl = "https://repo.steampowered.com/steamrt3c/images";
  hash = "sha256-0OIduVOLy9+lG0bwrLuoo9y9bl80WuQQpridm5C30J4=";
}
