# Generated by scripts/update.sh from Valve's runtime index. Do not edit.
{
  snapshot = "3c.0.20260824.257593";
  baseUrl = "https://repo.steampowered.com/steamrt3c/images";
  hash = "sha256-LyvkYbakNggo4gDhZE4YzZV+7cNqOOWh4To5J2MgtuI=";
}
