#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${GITHUB_OUTPUT:-/tmp/update-outputs.env}"
: >"$OUTPUT_FILE"
output() { echo "$1=$2" >>"$OUTPUT_FILE"; }
log() { echo "==> $*"; }
err() { echo "::error::$*"; }

readonly BASE_URL="https://client-update.fastly.steamstatic.com"
readonly RUNTIME_BASE="https://repo.steampowered.com/steamrt3c/images"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$repo_root/client-sources.nix"

runtime_out="$repo_root/runtime-source.nix"

pin_runtime() {
  local index snapshot old raw sri
  index="$(mktemp)"
  if ! curl -fsSL "$RUNTIME_BASE/latest-public-beta.txt" -o "$index"; then
    err "could not fetch the runtime index"
    output "error_type" "runtime-fetch"
    return 2
  fi
  snapshot="$(tr -d '[:space:]' <"$index")"
  rm -f "$index"
  if ! grep -qE '^[0-9]+[a-z]?\.[0-9]+\.[0-9]+\.[0-9]+$' <<<"$snapshot"; then
    err "the runtime index no longer names a snapshot: '$snapshot'"
    output "error_type" "runtime-shape"
    return 1
  fi
  old="$(sed -nE 's/^  snapshot = "(.*)";$/\1/p' "$runtime_out" 2>/dev/null | head -1)"
  if [ "$snapshot" = "$old" ]; then
    log "runtime already at $snapshot"
    return 0
  fi
  if ! raw="$(nix-prefetch-url --type sha256 "$RUNTIME_BASE/$snapshot/steam-runtime-steamrt-arm64.tar.xz" 2>/dev/null | tail -1)"; then
    err "could not fetch the runtime tarball for $snapshot"
    output "error_type" "runtime-fetch"
    return 2
  fi
  sri="$(nix hash to-sri --type sha256 "$raw")"
  {
    printf '# Generated by scripts/update.sh from Valve'"'"'s runtime index. Do not edit.\n'
    printf '{\n'
    printf '  snapshot = "%s";\n' "$snapshot"
    printf '  baseUrl = "%s";\n' "$RUNTIME_BASE"
    printf '  hash = "%s";\n' "$sri"
    printf '}\n'
  } >"$runtime_out"
  log "runtime $old -> $snapshot"
}

pin_runtime

output "package_name" "steam-arm64-client"
output "upstream_url" "$BASE_URL"

channel="${1:-}"
if [ -z "$channel" ] && [ -f "$out" ]; then
  channel="$(sed -nE 's/^  channel = "([a-z]+)";$/\1/p' "$out" | head -1)"
fi
channel="${channel:-publicbeta}"

case "$channel" in
publicbeta) manifest="steam_client_publicbeta_linuxarm64" ;;
stable) manifest="steam_client_linuxarm64" ;;
*)
  err "unknown channel '$channel' (publicbeta|stable)"
  output "updated" "false"
  output "error_type" "bad-channel"
  exit 1
  ;;
esac

old_version=""
if [ -f "$out" ]; then
  old_version="$(sed -nE 's/^  version = "([0-9]+)";$/\1/p' "$out" | head -1)"
fi
output "old_version" "$old_version"

vdf="$(mktemp)"
trap 'rm -f "$vdf"' EXIT
if ! curl -fsSL "$BASE_URL/$manifest" -o "$vdf"; then
  err "could not fetch $manifest"
  output "updated" "false"
  output "error_type" "manifest-fetch"
  exit 2
fi

version="$(awk -F'"' '/"version"/ { print $4; exit }' "$vdf")"
if [ -z "$version" ]; then
  err "no version in $manifest; the manifest shape changed"
  output "updated" "false"
  output "error_type" "manifest-shape"
  exit 1
fi
output "new_version" "$version"

wanted="$(grep -cE '^[[:blank:]]"[a-z0-9_]+(_all|_linuxarm64_linuxarm64)"$' "$vdf" || true)"
components="$(awk '
  /^\t"[a-z0-9_]+"$/ { name = $1; gsub(/"/, "", name) }
  /"file"/ { gsub(/"/, ""); file = $2 }
  /"sha2"[^v]/ {
    gsub(/"/, ""); sha = $2
    if (name ~ /(_all|_linuxarm64_linuxarm64)$/)
      printf "    %s = {\n      file = \"%s\";\n      sha256 = \"%s\";\n    };\n", name, file, sha
  }
' "$vdf")"

emitted="$(grep -c 'sha256 = ' <<<"$components" || true)"
if [ "$emitted" -eq 0 ] || [ "$emitted" -ne "$wanted" ]; then
  err "manifest lists $wanted linuxarm64 components but $emitted were pinned; the manifest shape changed"
  output "updated" "false"
  output "error_type" "manifest-shape"
  exit 1
fi

if [ "$version" = "$old_version" ]; then
  log "$channel already at $version"
  output "updated" "false"
  exit 0
fi

{
  printf '# Generated by scripts/update.sh from Valve'"'"'s client manifest. Do not edit.\n'
  printf '{\n'
  printf '  channel = "%s";\n' "$channel"
  printf '  version = "%s";\n' "$version"
  printf '  baseUrl = "%s";\n' "$BASE_URL"
  printf '  components = {\n'
  printf '%s\n' "$components"
  printf '  };\n'
  printf '}\n'
} >"$out"

log "verifying the new pin builds"
if ! nix build "$repo_root#default" --no-link; then
  err "the regenerated pin does not build"
  output "updated" "false"
  output "error_type" "build-error"
  exit 1
fi

log "$channel updated $old_version -> $version ($emitted components)"
output "updated" "true"
