#!/usr/bin/env bash
# Regenerates client-sources.nix from Valve's own client manifest.
# The manifest carries each component's sha256, so no download is needed.
set -o errexit
set -o nounset
set -o pipefail

readonly BASE_URL="https://client-update.fastly.steamstatic.com"

channel="${1:-publicbeta}"
case "$channel" in
publicbeta) manifest="steam_client_publicbeta_linuxarm64" ;;
stable) manifest="steam_client_linuxarm64" ;;
*)
  echo "update.sh: unknown channel '$channel' (publicbeta|stable)" >&2
  exit 1
  ;;
esac

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$repo_root/client-sources.nix"

vdf="$(mktemp)"
trap 'rm -f "$vdf"' EXIT
curl -fsSL "$BASE_URL/$manifest" -o "$vdf"

version="$(awk -F'"' '/"version"/ { print $4; exit }' "$vdf")"
if [ -z "$version" ]; then
  echo "update.sh: no version in $manifest; the manifest shape changed" >&2
  exit 1
fi

components="$(awk '
  /^\t"[a-z0-9_]+"$/ { name = $1; gsub(/"/, "", name) }
  /"file"/ { gsub(/"/, ""); file = $2 }
  /"sha2"[^v]/ {
    gsub(/"/, ""); sha = $2
    if (name ~ /(_all|_linuxarm64_linuxarm64)$/)
      printf "    %s = {\n      file = \"%s\";\n      sha256 = \"%s\";\n    };\n", name, file, sha
  }
' "$vdf")"

if [ -z "$components" ]; then
  echo "update.sh: no linuxarm64 components in $manifest; the manifest shape changed" >&2
  exit 1
fi

{
  printf '# Generated by scripts/update.sh from Valve'"'"'s client manifest. Do not edit.\n'
  printf '{\n'
  printf '  channel = "%s";\n' "$channel"
  printf '  version = "%s";\n' "$version"
  printf '  baseUrl = "%s";\n' "$BASE_URL"
  printf '  components = {\n'
  printf '%s\n' "$components"
  printf '  };\n'
  printf '}\n'
} >"$out"

printf 'update.sh: %s pinned at version %s (%d components)\n' \
  "$channel" "$version" "$(grep -c 'sha256 = ' "$out")"
